# Site settings
title: Peepul Tree Products
author: Rakesh Kamath
description: Fractional CTO services for growth-stage startups facing engineering challenges
favicon: "/assets/img/favicon.ico"

# Navigation bar links
navbar-links:
  About: "about"
  Services: "services"
  Why Choose Us: "why-choose"
  Testimonials: "testimonials"
  Case Studies: "case-studies"
  Contact: "contact"

# Add your social media links
social-network-links:
  email: "rakesh@peepul.ca"
  linkedin: "your-linkedin-profile"
  twitter: "your-twitter-handle"

# Select which social network share links to show in posts
share-links-active:
  twitter: true
  linkedin: true

# How to display the link to your website in the footer
url-pretty: "peepul.ca"

# Excerpt word length - Truncate the excerpt of each post to the specified number of words
excerpt_length: 50

# Add your Google Analytics ID here if you have one
#google_analytics: ""

# --- Don't need to touch anything below here (but you can if you want) --- #

# Output options (more information on Jekyll's site)
timezone: "America/Toronto"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 5

# Ruby Date Format to show dates of posts
date_format: "%B %-d, %Y"

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true  # add comments to all blog posts
      social-share: true # add social media sharing buttons to all blog posts
  -
    scope:
      path: "" # any file that's not a post will be a "page" layout by default
    values:
      layout: "page"

# Exclude these files from production site
exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - docs/

plugins:
  - jekyll-paginate
  - jekyll-sitemap

# Beautiful Jekyll / Dean Attali
# 2fc73a3a967e97599c9763d05e564189